name: docker-pipeline-sachin
on: push
jobs:
  docker-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print your Register No
        run: echo "Hello world - 22it038"

      - name: Checkout
        uses: actions/Checkout@v4.2.2

      - name: docker build
        run:  docker build -t ramsachin038/ml-22it038 .

      - name: docker images
        run:  docker images

      - name: login docker 
        uses:  docker/login-action@v3
        with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            passwoed: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker image to DockerHub
        run: docker push ramsachin038/ml-22it038 .
